on:
  push:
    branches:
      - main
    # Keep path list narrow. In other cases, manually start the workflow.
    paths:
      - "Dockerfile"
      - "build.sh"
  workflow_dispatch: {}

name: Build and Push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: dockerbuildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        env:
          BUILDER_NAME: ${{ steps.dockerbuildx.outputs.name }}
        run: |
          ./build.sh push
