on:
  push:
    branches:
      - main
    # Keep path list narrow. In other cases, manually start the workflow.
    paths:
      - "Dockerfile"
      - "build.sh"
  workflow_dispatch: {}

name: Build and Push

jobs:
  build:
    strategy:
      matrix:
        version: ["3.14.0a1", "3.14.0a1t"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          # Enable `sudo` to work inside a multi-architecture Docker build. See:
          #   https://github.com/docker/buildx/issues/1335
          #   https://github.com/multiarch/alpine/issues/32#issuecomment-604521491
          #   https://github.com/multiarch/qemu-user-static/issues/17
          docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
          # Actual build script.
          ./build.sh ${{ matrix.version }} push

      - name: Smoke Test
        run: |
          ./smoke-test.sh ${{ matrix.version }} 'mr0grog/circle-python-pre:${{ matrix.version }}'
