on:
  push:
    branches:
      - main
    # Keep path list narrow. In other cases, manually start the workflow.
    paths:
      - "Dockerfile"
      - "build.sh"
  workflow_dispatch: {}

name: Build and Push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Enable sudo in Docker Builds
        run: |
          # Enable `sudo` to work inside a multi-architecture Docker build. See:
          #   https://github.com/docker/buildx/issues/1335
          #   https://github.com/multiarch/alpine/issues/32#issuecomment-604521491
          #   https://github.com/multiarch/qemu-user-static/issues/17
          docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes

      - name: Build and Push
        run: |
          ./build.sh push
